name: selecao_app
description: A new Flutter project.
publish_to: "none"
version: 2.0.0+1

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_expanded_tile: ^0.3.7
  flutter_svg: ^2.0.6
  go_router: ^7.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  package_info_plus: ^4.0.2

flutter_launcher_icons: # dart pub run flutter_launcher_icons
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: assets/app/ic_launcher.png

flutter:
  uses-material-design: true

  assets:
    - assets/app/
    - assets/fonts/
    - assets/icons/

  fonts:
    - family: poppins
      fonts:
        - asset: assets/fonts/poppins.ttf
    - family: display
      fonts:
        - asset: assets/fonts/DisplayOTF.otf
