name: selecao_app
description: A new Flutter project.
publish_to: "none"
version: 2.0.0+1

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.6
  go_router: ^7.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  package_info_plus: ^4.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/app/
    - assets/fonts/
    - assets/icons/

  fonts:
    - family: poppins
      fonts:
        - asset: assets/fonts/poppins.ttf
    - family: digital
      fonts:
        - asset: assets/fonts/DS-DIGI.TTF
